vec3 GPU_WORLD_POSITION:TEXCOORD1;
vec3 VERTEX_CD_MTFACE:TEXCOORD2;
vec3 VERTEX_CD_ORCO:TEXCOORD3;
vec3 GPU_WORLD_NORMAL:TEXCOORD4;
vec3 VERTEX_CD_TANGENT:TEXCOORD5;
mat4 vWorldToLight:TEXCOORD6;
vec4 vPositionFromLight:TEXCOORD7;


vec3 a_position:POSITION;
vec2 a_texcoord0:TEXCOORD0;
vec3 a_normal:NORMAL;
vec3 a_tangent:TANGENT;
