vec3 GPU_WORLD_POSITION:TEXCOORD1;
vec3 VERTEX_CD_MTFACE:TEXCOORD2;
vec3 VERTEX_CD_ORCO:TEXCOORD3;
vec3 GPU_WORLD_NORMAL:TEXCOORD4;
mat4 vWorldToLight:TEXCOORD5;
vec4 vPositionFromLight:TEXCOORD6;


vec3 a_position:POSITION;
vec2 a_texcoord0:TEXCOORD0;
vec3 a_normal:NORMAL;
